### ISSUE TITLE
thanks

### ISSUE THREAD

**Issue by peterpanBest** [PLDaily/vue2-waterfall#10]
Hi, nice to konw u . this plugins is useful for me, thank u very much. do u have blog about ths realize the principle ofof plugins ? i want to learn taht :)

**Comment by PLDaily** [comment]
木有写文章，主要看 [imagesloaded](https://github.com/desandro/imagesloaded) 跟 [vue-waterfall](https://github.com/MopTym/vue-waterfall) 吧，结合了这俩个库
