### ISSUE TITLE
当数组清空 为空数组时 waterFall 的高度还是原来的高度 没有置为0

### ISSUE THREAD

**Issue by mumofa** [PLDaily/vue2-waterfall#16]
rt  希望可以自动处理一下

**Comment by PLDaily** [comment]
参考[https://github.com/PLDaily/vue2-waterfall/issues/7](https://github.com/PLDaily/vue2-waterfall/issues/7) 重新render一下

**Comment by mumofa** [comment]
> 参考#7 重新render一下

但如果这样的话。。。
不觉得有点糙吗。。。。
