### ISSUE TITLE
在移动端使用的时候，上拉加载经常会出现一边越来越高的情况

### ISSUE THREAD

**Issue by taizhengfs** [PLDaily/vue2-waterfall#17]
似乎存在高度计算出问题的情况？一旦有一边高度计算出现问题了，那这一边会越来越高，不知道是哪里出了问题，排查了好几天了，能帮忙看一下吗

**Comment by PLDaily** [comment]
用1.0.9这个版本吧，2.0的布局方式变了会存在这个问题

**Comment by taizhengfs** [comment]
可以了，感谢！但是似乎 gutterWidth 这个属性不生效，不只是哪里还要配置吗？

**Comment by smidaxia** [comment]
我也遇到同样的问题，会有一边高的情况，如果降级的话，会出现其他的情况，比如左边的空隙没了

**Comment by taizhengfs** [comment]
我之前自己写了一个，按照多列来排序，哪边高往哪边塞，就会出现这种一高一低的情况。没找到问题再哪里，看来还是得用老的绝对布局的方式来排列。空隙的话这个插件建议在里面用padding来处理一下

**Comment by cqwanghao** [comment]
我用vue的缓存，用的这个配置:percent="[1,1]"，然后从其他页面跳转进来，宽度为0了，导致显示不正常

**Comment by PLDaily** [comment]
使用percent的时候gutterWidth不起作用，需要间隔的话在item上加padding留白

**Comment by cqwanghao** [comment]
![image](https://user-images.githubusercontent.com/21287575/46784380-78150c80-cd60-11e8-840d-6d7e287e21a9.png)
开始进页面正常，从其他页面返回之后就不正常了

**Comment by PLDaily** [comment]
用了keep-alive？重新render一下

**Comment by cqwanghao** [comment]
就是用了keep-alive，就是需要就是不要重新渲染呢，怎么处理呢

**Comment by PLDaily** [comment]
1.0.9 这个版本只能重新渲染，2.0.1这个我还没试过

**Comment by taizhengfs** [comment]
这个版本还有一个问题- - 安卓webview，如果页面被后台默默渲染了，假设四个tab，瀑布流在第三个tab，当我点击瀑布流tab之前页面其实已经加载好了，当点击这个tab的时候，这个情况下瀑布流的布局间距总是各种不对。但是一刷新就好了- -

**Comment by PLDaily** [comment]
升级最新版
