### ISSUE TITLE
顺序显示不正常

### ISSUE THREAD

**Issue by yixiaoyi0522** [PLDaily/vue2-waterfall#20]
展示出数组的索引，分3列，出来的是0,1,2,10,11,12，6,7,8......10,11,12出现两次，没有3,4,5请问是什么原因

**Comment by yixiaoyi0522** [comment]
而且每次刷新出来的排列顺序会不同

**Comment by PLDaily** [comment]
https://github.com/PLDaily/vue2-waterfall/issues/17
