### ISSUE TITLE
流体百分比布局和子组件水平间距冲突

### ISSUE THREAD

**Issue by yuzhengbo** [PLDaily/vue2-waterfall#28]
设置percent为之后， gutterWidth的水平间距就失效了， 能不能保留间距的情况下，自适应子组件宽度

**Comment by PLDaily** [comment]
子组件设置padding

**Comment by yuzhengbo** [comment]
> 子组件设置填充

是个解决办法， 如果能解决两个参数之间的冲突就更好了
