### ISSUE TITLE
列表只有1个数据的时候 宽度不管用

### ISSUE THREAD

**Issue by duansiyu** [PLDaily/vue2-waterfall#29]
![image](https://user-images.githubusercontent.com/17777911/59961391-aeb73f80-9509-11e9-98cc-53006a378c0b.png)
![image](https://user-images.githubusercontent.com/17777911/59961394-baa30180-9509-11e9-98ad-39300b5b9d0f.png)
我设置了每行5个 这里是什么原因出现十几个呢？

**Comment by duansiyu** [comment]
> `[](url)`

**Comment by sinhang** [comment]
你解决这个问题了吗？我现在也碰到这个问题了
