### ISSUE TITLE
瀑布流布局时，最后几个错位了。版本 2.0.1

### ISSUE THREAD

**Issue by MrHzq** [PLDaily/vue2-waterfall#30]
## 情况一：
![image](https://user-images.githubusercontent.com/24823464/61105589-e2eca300-a4ac-11e9-82ae-7c80f0e7f3d0.png)
## 情况二：
![image](https://user-images.githubusercontent.com/24823464/61105631-129bab00-a4ad-11e9-9e1f-c63073988bf8.png)

**Comment by MrHzq** [comment]
目前 改用 1.0.9 版本的就可以了

**Comment by Jonathan-Rao** [comment]
@MrHzq 1.0.9怎么使用

**Comment by PLDaily** [comment]
升级最新版
