### ISSUE TITLE
问下align属性怎么设置了没有效果

### ISSUE THREAD

**Issue by thelongmarch** [PLDaily/vue2-waterfall#5]
默认是center ，left和right为啥没效果

**Comment by PLDaily** [comment]
代码贴出来看下

**Comment by thelongmarch** [comment]
<Waterfall  :align="left" :gutterWidth="10" :gutterHeight="10" >
              <WaterfallItem v-for="(items,index) in resultList" :key="index" :width="400" :order="index" >
                <div class="localImg">
                  <div class="img">
                    <img :src="items.imgUrl" alt="图片" width="100%" class="img-detail">
                  </div>
                  <div class="local">
                    <p class="local-title">{{items.title}}</p>
                  </div>
                  <template v-for="(item,index) in items.list">
                    <div class="materialTitle">
                      <p class="list-title">{{item.title}}</p>
                      <div class="little-img">
                        <img :src="item.littleImg" alt="" width="80px">
                      </div>
                    </div>
                  </template>
                  <div class="localButton">
                    <el-button type="primary">编辑</el-button>
                    <el-button type="primary">删除</el-button>
                  </div>
                </div>
              </WaterfallItem>
            </Waterfall>

**Comment by thelongmarch** [comment]
![image](https://user-images.githubusercontent.com/8542608/39556773-67380090-4eb5-11e8-971d-3fa46db1b1fe.png)

**Comment by thelongmarch** [comment]
qq2454424641

**Comment by PLDaily** [comment]
```
<Waterfall :align="'left'" :gutterWidth="30" :gutterHeight="30">
</Waterfall>
```
你这样写left是一个变量
```
<Waterfall :align="left" :gutterWidth="30" :gutterHeight="30">
</Waterfall>
```
```
data () {
  return {
    left: 'left'
  }
}
```

**Comment by thelongmarch** [comment]
thanks,糊涂了
