### ISSUE TITLE
饿了么组件tab切换

### ISSUE THREAD

**Issue by thelongmarch** [PLDaily/vue2-waterfall#6]
大佬，又遇到一个问题，饿了么组件tab切换失效，实现的方式页面加载时把两个tab标签里面的数据都获取了，然后切换。默认的tab瀑布流可以，第二个tab瀑布流失效，白屏。

**Comment by PLDaily** [comment]
瀑布流data数据更新一下就好了

**Comment by thelongmarch** [comment]
已经有数据了，就是在初始化页面的时候同时获取两个tab的数据，只显示一个tab，因为tab切换不能每切换一次调取一次接口。
