### ISSUE TITLE
Best way to remove an item from the waterfall?

### ISSUE THREAD

**Issue by Pitu** [PLDaily/vue2-waterfall#7]
I use waterfall to display user uploads. When a user deletes a file, I remove the element from the waterfall but then it becomes broken as seen on [this video](https://lolisafe.moe/ni946nf4.mp4). Is there a way to manually trigger a re-render / re-sort of the waterfall items?

**Comment by PLDaily** [comment]
```
<vue2-waterfall v-if="reset"></vue2-waterfall>
```

```
this.reset = false
this.$nextTick(() => {
  this.reset = true
})
```

try this.

**Comment by Pitu** [comment]
That did the trick, thanks!
